CREATE TABLE Cartinhas (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    NomeCrianca VARCHAR(255) NOT NULL,
    Rua VARCHAR(150) NOT NULL,
    Numero VARCHAR(20) NOT NULL,
    Bairro VARCHAR(150) NOT NULL,
    Cidade VARCHAR(150) NOT NULL,
    Estado VARCHAR(50) NOT NULL,
    Cep VARCHAR(20) NOT NULL,
    Idade INT NOT NULL,
    MensagemCartinha VARCHAR(500) NOT NULL
);